// backend/utils/sgpaCalculator.js

const subjectsByBranch = {

    CS: {
       "First Year": [
        { "code": "BMATS101", "credits": 4 },
        { "code": "BPHYS102", "credits": 4 },
        { "code": "BPOPS103", "credits": 3 },
        { "code": "BESCK104A", "credits": 3 },
        { "code": "BESCK104B", "credits": 3 },
        { "code": "BESCK104C", "credits": 3 },
        { "code": "BESCK104D", "credits": 3 },
        { "code": "BESCK104E", "credits": 3 },
        { "code": "BETCK105A", "credits": 3 },
        { "code": "BETCK105B", "credits": 3 },
        { "code": "BETCK105C", "credits": 3 },
        { "code": "BETCK105D", "credits": 3 },
        { "code": "BETCK105E", "credits": 3 },
        { "code": "BETCK105F", "credits": 3 },
        { "code": "BETCK105G", "credits": 3 },
        { "code": "BETCK105H", "credits": 3 },
        { "code": "BETCK105I", "credits": 3 },
        { "code": "BETCK105J", "credits": 3 },
        { "code": "BPLCK105A", "credits": 3 },
        { "code": "BPLCK105B", "credits": 3 },
        { "code": "BPLCK105C", "credits": 3 },
        { "code": "BPLCK105D", "credits": 3 },
        { "code": "BENGK106", "credits": 1 },
        { "code": "BPWSK106", "credits": 1 },
        { "code": "BKSKK107", "credits": 1 },
        { "code": "BKBKK107", "credits": 1 },
        { "code": "BICOK107", "credits": 1 },
        { "code": "BIDTK158", "credits": 1 },
        { "code": "BSFHK158", "credits": 1 },
        { "code": "BMATC101", "credits": 4 },
        { "code": "BPHYC102", "credits": 4 },
        { "code": "BCIVC103", "credits": 3 },
        { "code": "BMATE101", "credits": 4 },
        { "code": "BPHYE102", "credits": 4 },
        { "code": "BEEE103", "credits": 3 },
        { "code": "BMATM101", "credits": 4 },
        { "code": "BPHYM102", "credits": 4 },
        { "code": "BEMEM103", "credits": 3 },
        { "code": "BMATS201", "credits": 4 },
        { "code": "BCHES202", "credits": 4 },
        { "code": "BCEDK203", "credits": 3 },
        { "code": "BESCK204A", "credits": 3 },
        { "code": "BESCK204B", "credits": 3 },
        { "code": "BESCK204C", "credits": 3 },
        { "code": "BESCK204D", "credits": 3 },
        { "code": "BESCK204E", "credits": 3 },
        { "code": "BPLCK205A", "credits": 3 },
        { "code": "BPLCK205B", "credits": 3 },
        { "code": "BPLCK205C", "credits": 3 },
        { "code": "BPLCK205D", "credits": 3 },
        { "code": "BETCK205A", "credits": 3 },
        { "code": "BETCK205B", "credits": 3 },
        { "code": "BETCK205C", "credits": 3 },
        { "code": "BETCK205D", "credits": 3 },
        { "code": "BETCK205E", "credits": 3 },
        { "code": "BETCK205F", "credits": 3 },
        { "code": "BETCK205G", "credits": 3 },
        { "code": "BETCK205H", "credits": 3 },
        { "code": "BETCK205I", "credits": 3 },
        { "code": "BETCK205J", "credits": 3 },
        { "code": "BENGK206", "credits": 1 },
        { "code": "BPWSK206", "credits": 1 },
        { "code": "BICOK207", "credits": 1 },
        { "code": "BKSKK207", "credits": 1 },
        { "code": "BKBKK207", "credits": 1 },
        { "code": "BSFHK258", "credits": 1 },
        { "code": "KIDTK258", "credits": 1 },
        { "code": "BMATC201", "credits": 4 },
        { "code": "BCHEC202", "credits": 4 },
        { "code": "BMATE201", "credits": 4 },
        { "code": "BCHEE202", "credits": 4 },
        { "code": "BCEDK203", "credits": 3 },
        { "code": "BMATM201", "credits": 4 },
        { "code": "BCHEM202", "credits": 4 },
        { "code": "BMATS101", "credits": 4 },
        { "code": "BCHES102", "credits": 4 },
        { "code": "BCEDK103", "credits": 3 },
        { "code": "BESCK104A", "credits": 3 },
        { "code": "BESCK104B", "credits": 3 },
        { "code": "BESCK104C", "credits": 3 },
        { "code": "BESCK104D", "credits": 3 },
        { "code": "BESCK104E", "credits": 3 },
        { "code": "BETCK105A", "credits": 3 },
        { "code": "BETCK105B", "credits": 3 },
        { "code": "BETCK105C", "credits": 3 },
        { "code": "BETCK105D", "credits": 3 },
        { "code": "BETCK105E", "credits": 3 },
        { "code": "BETCK105F", "credits": 3 },
        { "code": "BETCK105G", "credits": 3 },
        { "code": "BETCK105H", "credits": 3 },
        { "code": "BETCK105I", "credits": 3 },
        { "code": "BETCK105J", "credits": 3 },
        { "code": "BPLCK105A", "credits": 3 },
        { "code": "BPLCK105B", "credits": 3 },
        { "code": "BPLCK105C", "credits": 3 },
        { "code": "BPLCK105D", "credits": 3 },
        { "code": "BPWSK106", "credits": 1 },
        { "code": "BENGK106", "credits": 1 },
        { "code": "BICOK107", "credits": 1 },
        { "code": "BKSKK107", "credits": 1 },
        { "code": "BKBKK107", "credits": 1 },
        { "code": "BSFHK158", "credits": 1 },
        { "code": "BIDTK158", "credits": 1 }
      ],

      "3rd Semester": [
        { code: "BCS301", credits: 4 },
        { code: "BCS302", credits: 4 },
        { code: "BCS303", credits: 4 },
        { code: "BCS304", credits: 3 },
        { code: "BCSL305", credits: 1 },
        { code: "BCS306A", credits: 3 },
        { code: "BCS306B", credits: 3 },
        { code: "BCS306C", credits: 3 },
        { code: "BCS306D", credits: 3 },
        { code: "BSCK307", credits: 1 },
        { code: "BCS358A", credits: 1 },
        { code: "BCS358B", credits: 1 },
        { code: "BCS358C", credits: 1 },
        { code: "BCS358D", credits: 1 },
        { code: "BNSK359", credits: 0 },
        { code: "BPEK359", credits: 0 },
        { code: "BYOK359", credits: 0 },
      ],
  
      "4th Semester": [
        { code: "BCS401", credits: 3 },
        { code: "BCS402", credits: 4 },
        { code: "BCS403", credits: 4 },
        { code: "BCSL404", credits: 1 },
        { code: "BCS405A", credits: 3 },
        { code: "BCS405B", credits: 3 },
        { code: "BCS405C", credits: 3 },
        { code: "BCS405D", credits: 3 },
        { code: "BCS456A", credits: 1 },
        { code: "BCS456B", credits: 1 },
        { code: "BCS456C", credits: 1 },
        { code: "BCS456D", credits: 1 },
        { code: "BBOC407", credits: 2 },
        { code: "BUHK408", credits: 1 },
        { code: "BNSK459", credits: 0 },
        { code: "BPEK459", credits: 0 },
        { code: "BYOK459", credits: 0 },
      ],
  
      "5th Semester": [
        { code: "BCS501", credits: 4 },
        { code: "BCS502", credits: 4 },
        { code: "BCS503", credits: 4 },
        { code: "BCSL504", credits: 1 },
        { code: "BCS515A", credits: 3 },
        { code: "BCS515B", credits: 3 },
        { code: "BCS515C", credits: 3 },
        { code: "BCS515D", credits: 3 },
        { code: "BCS586", credits: 2 },
        { code: "BRMK557", credits: 3 },
        { code: "BCS508", credits: 1 },
        { code: "BNSK559", credits: 0 },
        { code: "BPEK559", credits: 0 },
        { code: "BYOK559", credits: 0 },
      ],
    },
  
  
    
    IS: {

      "First Year": [
        { "code": "BMATS101", "credits": 4 },
        { "code": "BPHYS102", "credits": 4 },
        { "code": "BPOPS103", "credits": 3 },
        { "code": "BESCK104A", "credits": 3 },
        { "code": "BESCK104B", "credits": 3 },
        { "code": "BESCK104C", "credits": 3 },
        { "code": "BESCK104D", "credits": 3 },
        { "code": "BESCK104E", "credits": 3 },
        { "code": "BETCK105A", "credits": 3 },
        { "code": "BETCK105B", "credits": 3 },
        { "code": "BETCK105C", "credits": 3 },
        { "code": "BETCK105D", "credits": 3 },
        { "code": "BETCK105E", "credits": 3 },
        { "code": "BETCK105F", "credits": 3 },
        { "code": "BETCK105G", "credits": 3 },
        { "code": "BETCK105H", "credits": 3 },
        { "code": "BETCK105I", "credits": 3 },
        { "code": "BETCK105J", "credits": 3 },
        { "code": "BPLCK105A", "credits": 3 },
        { "code": "BPLCK105B", "credits": 3 },
        { "code": "BPLCK105C", "credits": 3 },
        { "code": "BPLCK105D", "credits": 3 },
        { "code": "BENGK106", "credits": 1 },
        { "code": "BPWSK106", "credits": 1 },
        { "code": "BKSKK107", "credits": 1 },
        { "code": "BKBKK107", "credits": 1 },
        { "code": "BICOK107", "credits": 1 },
        { "code": "BIDTK158", "credits": 1 },
        { "code": "BSFHK158", "credits": 1 },
        { "code": "BMATC101", "credits": 4 },
        { "code": "BPHYC102", "credits": 4 },
        { "code": "BCIVC103", "credits": 3 },
        { "code": "BMATE101", "credits": 4 },
        { "code": "BPHYE102", "credits": 4 },
        { "code": "BEEE103", "credits": 3 },
        { "code": "BMATM101", "credits": 4 },
        { "code": "BPHYM102", "credits": 4 },
        { "code": "BEMEM103", "credits": 3 },
        { "code": "BMATS201", "credits": 4 },
        { "code": "BCHES202", "credits": 4 },
        { "code": "BCEDK203", "credits": 3 },
        { "code": "BESCK204A", "credits": 3 },
        { "code": "BESCK204B", "credits": 3 },
        { "code": "BESCK204C", "credits": 3 },
        { "code": "BESCK204D", "credits": 3 },
        { "code": "BESCK204E", "credits": 3 },
        { "code": "BPLCK205A", "credits": 3 },
        { "code": "BPLCK205B", "credits": 3 },
        { "code": "BPLCK205C", "credits": 3 },
        { "code": "BPLCK205D", "credits": 3 },
        { "code": "BETCK205A", "credits": 3 },
        { "code": "BETCK205B", "credits": 3 },
        { "code": "BETCK205C", "credits": 3 },
        { "code": "BETCK205D", "credits": 3 },
        { "code": "BETCK205E", "credits": 3 },
        { "code": "BETCK205F", "credits": 3 },
        { "code": "BETCK205G", "credits": 3 },
        { "code": "BETCK205H", "credits": 3 },
        { "code": "BETCK205I", "credits": 3 },
        { "code": "BETCK205J", "credits": 3 },
        { "code": "BENGK206", "credits": 1 },
        { "code": "BPWSK206", "credits": 1 },
        { "code": "BICOK207", "credits": 1 },
        { "code": "BKSKK207", "credits": 1 },
        { "code": "BKBKK207", "credits": 1 },
        { "code": "BSFHK258", "credits": 1 },
        { "code": "KIDTK258", "credits": 1 },
        { "code": "BMATC201", "credits": 4 },
        { "code": "BCHEC202", "credits": 4 },
        { "code": "BMATE201", "credits": 4 },
        { "code": "BCHEE202", "credits": 4 },
        { "code": "BCEDK203", "credits": 3 },
        { "code": "BMATM201", "credits": 4 },
        { "code": "BCHEM202", "credits": 4 },
        { "code": "BMATS101", "credits": 4 },
        { "code": "BCHES102", "credits": 4 },
        { "code": "BCEDK103", "credits": 3 },
        { "code": "BESCK104A", "credits": 3 },
        { "code": "BESCK104B", "credits": 3 },
        { "code": "BESCK104C", "credits": 3 },
        { "code": "BESCK104D", "credits": 3 },
        { "code": "BESCK104E", "credits": 3 },
        { "code": "BETCK105A", "credits": 3 },
        { "code": "BETCK105B", "credits": 3 },
        { "code": "BETCK105C", "credits": 3 },
        { "code": "BETCK105D", "credits": 3 },
        { "code": "BETCK105E", "credits": 3 },
        { "code": "BETCK105F", "credits": 3 },
        { "code": "BETCK105G", "credits": 3 },
        { "code": "BETCK105H", "credits": 3 },
        { "code": "BETCK105I", "credits": 3 },
        { "code": "BETCK105J", "credits": 3 },
        { "code": "BPLCK105A", "credits": 3 },
        { "code": "BPLCK105B", "credits": 3 },
        { "code": "BPLCK105C", "credits": 3 },
        { "code": "BPLCK105D", "credits": 3 },
        { "code": "BPWSK106", "credits": 1 },
        { "code": "BENGK106", "credits": 1 },
        { "code": "BICOK107", "credits": 1 },
        { "code": "BKSKK107", "credits": 1 },
        { "code": "BKBKK107", "credits": 1 },
        { "code": "BSFHK158", "credits": 1 },
        { "code": "BIDTK158", "credits": 1 }
      ],

      "3rd Semester": [
        { code: "BCS301", credits: 4 },
        { code: "BCS302", credits: 4 },
        { code: "BCS303", credits: 4 },
        { code: "BCS304", credits: 3 },
        { code: "BCSL305", credits: 1 },
        { code: "BCS306A", credits: 3 },
        { code: "BDS306B", credits: 3 },
        { code: "BDS306C", credits: 3 },
        { code: "BAI306D", credits: 3 },
        { code: "BSCK307", credits: 1 },
        { code: "BCS358A", credits: 1 },
        { code: "BAI358B", credits: 1 },
        { code: "BCS358C", credits: 1 },
        { code: "BAI358D", credits: 1 },
        { code: "BNSK359", credits: 0 },
        { code: "BPEK359", credits: 0 },
        { code: "BYOK359", credits: 0 },
      ],
      "4th Semester": [
        { code: "BCS401", credits: 3 },
        { code: "BIS402", credits: 4 },
        { code: "BCS403", credits: 4 },
        { code: "BCSL404", credits: 1 },
        { code: "BCS405A", credits: 3 },
        { code: "BCS405B", credits: 3 },
        { code: "BCS405C", credits: 3 },
        { code: "BCS405D", credits: 3 },
        { code: "BCS456A", credits: 1 },
        { code: "BCS456B", credits: 1 },
        { code: "BCS456C", credits: 1 },
        { code: "BCSL456D", credits: 1 },
        { code: "BBOC407", credits: 3 },
        { code: "BUHK408", credits: 1 },
        { code: "BNSK459", credits: 0 },
        { code: "BPEK459", credits: 0 },
        { code: "BYOK459", credits: 0 },
      ],
      "5th Semester": [
        { code: "BCS501", credits: 4 },
        { code: "BCS502", credits: 4 },
        { code: "BCS503", credits: 4 },
        { code: "BAIL504", credits: 1 },
        { code: "BAI515A", credits: 3 },
        { code: "BCS515B", credits: 3 },
        { code: "BCS515C", credits: 3 },
        { code: "BCS515D", credits: 3 },
        { code: "BIS586", credits: 2 },
        { code: "BRMK557", credits: 3 },
        { code: "BCS508", credits: 1 },
        { code: "BNSK559", credits: 0 },
        { code: "BPEK559", credits: 0 },
        { code: "BYOK559", credits: 0 },
      ],
    },
    EC: {

      "First Year": [
        { "code": "BMATS101", "credits": 4 },
        { "code": "BPHYS102", "credits": 4 },
        { "code": "BPOPS103", "credits": 3 },
        { "code": "BESCK104A", "credits": 3 },
        { "code": "BESCK104B", "credits": 3 },
        { "code": "BESCK104C", "credits": 3 },
        { "code": "BESCK104D", "credits": 3 },
        { "code": "BESCK104E", "credits": 3 },
        { "code": "BETCK105A", "credits": 3 },
        { "code": "BETCK105B", "credits": 3 },
        { "code": "BETCK105C", "credits": 3 },
        { "code": "BETCK105D", "credits": 3 },
        { "code": "BETCK105E", "credits": 3 },
        { "code": "BETCK105F", "credits": 3 },
        { "code": "BETCK105G", "credits": 3 },
        { "code": "BETCK105H", "credits": 3 },
        { "code": "BETCK105I", "credits": 3 },
        { "code": "BETCK105J", "credits": 3 },
        { "code": "BPLCK105A", "credits": 3 },
        { "code": "BPLCK105B", "credits": 3 },
        { "code": "BPLCK105C", "credits": 3 },
        { "code": "BPLCK105D", "credits": 3 },
        { "code": "BENGK106", "credits": 1 },
        { "code": "BPWSK106", "credits": 1 },
        { "code": "BKSKK107", "credits": 1 },
        { "code": "BKBKK107", "credits": 1 },
        { "code": "BICOK107", "credits": 1 },
        { "code": "BIDTK158", "credits": 1 },
        { "code": "BSFHK158", "credits": 1 },
        { "code": "BMATC101", "credits": 4 },
        { "code": "BPHYC102", "credits": 4 },
        { "code": "BCIVC103", "credits": 3 },
        { "code": "BMATE101", "credits": 4 },
        { "code": "BPHYE102", "credits": 4 },
        { "code": "BEEE103", "credits": 3 },
        { "code": "BMATM101", "credits": 4 },
        { "code": "BPHYM102", "credits": 4 },
        { "code": "BEMEM103", "credits": 3 },
        { "code": "BMATS201", "credits": 4 },
        { "code": "BCHES202", "credits": 4 },
        { "code": "BCEDK203", "credits": 3 },
        { "code": "BESCK204A", "credits": 3 },
        { "code": "BESCK204B", "credits": 3 },
        { "code": "BESCK204C", "credits": 3 },
        { "code": "BESCK204D", "credits": 3 },
        { "code": "BESCK204E", "credits": 3 },
        { "code": "BPLCK205A", "credits": 3 },
        { "code": "BPLCK205B", "credits": 3 },
        { "code": "BPLCK205C", "credits": 3 },
        { "code": "BPLCK205D", "credits": 3 },
        { "code": "BETCK205A", "credits": 3 },
        { "code": "BETCK205B", "credits": 3 },
        { "code": "BETCK205C", "credits": 3 },
        { "code": "BETCK205D", "credits": 3 },
        { "code": "BETCK205E", "credits": 3 },
        { "code": "BETCK205F", "credits": 3 },
        { "code": "BETCK205G", "credits": 3 },
        { "code": "BETCK205H", "credits": 3 },
        { "code": "BETCK205I", "credits": 3 },
        { "code": "BETCK205J", "credits": 3 },
        { "code": "BENGK206", "credits": 1 },
        { "code": "BPWSK206", "credits": 1 },
        { "code": "BICOK207", "credits": 1 },
        { "code": "BKSKK207", "credits": 1 },
        { "code": "BKBKK207", "credits": 1 },
        { "code": "BSFHK258", "credits": 1 },
        { "code": "KIDTK258", "credits": 1 },
        { "code": "BMATC201", "credits": 4 },
        { "code": "BCHEC202", "credits": 4 },
        { "code": "BMATE201", "credits": 4 },
        { "code": "BCHEE202", "credits": 4 },
        { "code": "BCEDK203", "credits": 3 },
        { "code": "BMATM201", "credits": 4 },
        { "code": "BCHEM202", "credits": 4 },
        { "code": "BMATS101", "credits": 4 },
        { "code": "BCHES102", "credits": 4 },
        { "code": "BCEDK103", "credits": 3 },
        { "code": "BESCK104A", "credits": 3 },
        { "code": "BESCK104B", "credits": 3 },
        { "code": "BESCK104C", "credits": 3 },
        { "code": "BESCK104D", "credits": 3 },
        { "code": "BESCK104E", "credits": 3 },
        { "code": "BETCK105A", "credits": 3 },
        { "code": "BETCK105B", "credits": 3 },
        { "code": "BETCK105C", "credits": 3 },
        { "code": "BETCK105D", "credits": 3 },
        { "code": "BETCK105E", "credits": 3 },
        { "code": "BETCK105F", "credits": 3 },
        { "code": "BETCK105G", "credits": 3 },
        { "code": "BETCK105H", "credits": 3 },
        { "code": "BETCK105I", "credits": 3 },
        { "code": "BETCK105J", "credits": 3 },
        { "code": "BPLCK105A", "credits": 3 },
        { "code": "BPLCK105B", "credits": 3 },
        { "code": "BPLCK105C", "credits": 3 },
        { "code": "BPLCK105D", "credits": 3 },
        { "code": "BPWSK106", "credits": 1 },
        { "code": "BENGK106", "credits": 1 },
        { "code": "BICOK107", "credits": 1 },
        { "code": "BKSKK107", "credits": 1 },
        { "code": "BKBKK107", "credits": 1 },
        { "code": "BSFHK158", "credits": 1 },
        { "code": "BIDTK158", "credits": 1 }
      ],

      "3rd Semester": [
        { code: "BMATEC301", credits: 3 },
        { code: "BEC302", credits: 4 },
        { code: "BEC303", credits: 4 },
        { code: "BEC304", credits: 3 },
        { code: "BECL305", credits: 1 },
        { code: "BEC306A", credits: 3 },
        { code: "BEC306B", credits: 3 },
        { code: "BEC306C", credits: 3 },
        { code: "BEC306D", credits: 3 },
        { code: "BSCK307", credits: 1 },
        { code: "BEC358A", credits: 1 },
        { code: "BEC358B", credits: 1 },
        { code: "BEC358C", credits: 1 },
        { code: "BEC358D", credits: 1 },
        { code: "BNSK359", credits: 0 },
        { code: "BPEK359", credits: 0 },
        { code: "BYOK359", credits: 0 },
      ],
  
      "4th Semester": [
        { code: "BEC401", credits: 3 },
        { code: "BEC402", credits: 4 },
        { code: "BEC403", credits: 4 },
        { code: "BECL404", credits: 1 },
        { code: "BECL305", credits: 1 },
        { code: "BEC405A", credits: 3 },
        { code: "BEC405B", credits: 3 },
        { code: "BEC405C", credits: 3 },
        { code: "BEC405D", credits: 3 },
        { code: "BEC456A", credits: 1 },
        { code: "BEC456B", credits: 1 },
        { code: "BEC456C", credits: 1 },
        { code: "BEC456D", credits: 1 },
        { code: "BBOK407", credits: 3 },
        { code: "BUHK408", credits: 1 },
        { code: "BNSK459", credits: 0 },
        { code: "BPEK459", credits: 0 },
        { code: "BYOK459", credits: 0 },
      ],
  
      "5th Semester": [
        { code: "BEC501", credits: 3 },
        { code: "BEC502", credits: 4 },
        { code: "BEC503", credits: 4 },
        { code: "BECL504", credits: 1 },
        { code: "BEC515A", credits: 3 },
        { code: "BEC515B", credits: 3 },
        { code: "BEC515C", credits: 3 },
        { code: "BEC515D", credits: 3 },
        { code: "BEC586", credits: 2 },
        { code: "BRMK557", credits: 3 },
        { code: "BESK508", credits: 2 },
        { code: "BNSK559", credits: 0 },
        { code: "BPEK559", credits: 0 },
        { code: "BYOK559", credits: 0 },
      ],
    },
    ME: {

      "First Year": [
        { "code": "BMATS101", "credits": 4 },
        { "code": "BPHYS102", "credits": 4 },
        { "code": "BPOPS103", "credits": 3 },
        { "code": "BESCK104A", "credits": 3 },
        { "code": "BESCK104B", "credits": 3 },
        { "code": "BESCK104C", "credits": 3 },
        { "code": "BESCK104D", "credits": 3 },
        { "code": "BESCK104E", "credits": 3 },
        { "code": "BETCK105A", "credits": 3 },
        { "code": "BETCK105B", "credits": 3 },
        { "code": "BETCK105C", "credits": 3 },
        { "code": "BETCK105D", "credits": 3 },
        { "code": "BETCK105E", "credits": 3 },
        { "code": "BETCK105F", "credits": 3 },
        { "code": "BETCK105G", "credits": 3 },
        { "code": "BETCK105H", "credits": 3 },
        { "code": "BETCK105I", "credits": 3 },
        { "code": "BETCK105J", "credits": 3 },
        { "code": "BPLCK105A", "credits": 3 },
        { "code": "BPLCK105B", "credits": 3 },
        { "code": "BPLCK105C", "credits": 3 },
        { "code": "BPLCK105D", "credits": 3 },
        { "code": "BENGK106", "credits": 1 },
        { "code": "BPWSK106", "credits": 1 },
        { "code": "BKSKK107", "credits": 1 },
        { "code": "BKBKK107", "credits": 1 },
        { "code": "BICOK107", "credits": 1 },
        { "code": "BIDTK158", "credits": 1 },
        { "code": "BSFHK158", "credits": 1 },
        { "code": "BMATC101", "credits": 4 },
        { "code": "BPHYC102", "credits": 4 },
        { "code": "BCIVC103", "credits": 3 },
        { "code": "BMATE101", "credits": 4 },
        { "code": "BPHYE102", "credits": 4 },
        { "code": "BEEE103", "credits": 3 },
        { "code": "BMATM101", "credits": 4 },
        { "code": "BPHYM102", "credits": 4 },
        { "code": "BEMEM103", "credits": 3 },
        { "code": "BMATS201", "credits": 4 },
        { "code": "BCHES202", "credits": 4 },
        { "code": "BCEDK203", "credits": 3 },
        { "code": "BESCK204A", "credits": 3 },
        { "code": "BESCK204B", "credits": 3 },
        { "code": "BESCK204C", "credits": 3 },
        { "code": "BESCK204D", "credits": 3 },
        { "code": "BESCK204E", "credits": 3 },
        { "code": "BPLCK205A", "credits": 3 },
        { "code": "BPLCK205B", "credits": 3 },
        { "code": "BPLCK205C", "credits": 3 },
        { "code": "BPLCK205D", "credits": 3 },
        { "code": "BETCK205A", "credits": 3 },
        { "code": "BETCK205B", "credits": 3 },
        { "code": "BETCK205C", "credits": 3 },
        { "code": "BETCK205D", "credits": 3 },
        { "code": "BETCK205E", "credits": 3 },
        { "code": "BETCK205F", "credits": 3 },
        { "code": "BETCK205G", "credits": 3 },
        { "code": "BETCK205H", "credits": 3 },
        { "code": "BETCK205I", "credits": 3 },
        { "code": "BETCK205J", "credits": 3 },
        { "code": "BENGK206", "credits": 1 },
        { "code": "BPWSK206", "credits": 1 },
        { "code": "BICOK207", "credits": 1 },
        { "code": "BKSKK207", "credits": 1 },
        { "code": "BKBKK207", "credits": 1 },
        { "code": "BSFHK258", "credits": 1 },
        { "code": "KIDTK258", "credits": 1 },
        { "code": "BMATC201", "credits": 4 },
        { "code": "BCHEC202", "credits": 4 },
        { "code": "BMATE201", "credits": 4 },
        { "code": "BCHEE202", "credits": 4 },
        { "code": "BCEDK203", "credits": 3 },
        { "code": "BMATM201", "credits": 4 },
        { "code": "BCHEM202", "credits": 4 },
        { "code": "BMATS101", "credits": 4 },
        { "code": "BCHES102", "credits": 4 },
        { "code": "BCEDK103", "credits": 3 },
        { "code": "BESCK104A", "credits": 3 },
        { "code": "BESCK104B", "credits": 3 },
        { "code": "BESCK104C", "credits": 3 },
        { "code": "BESCK104D", "credits": 3 },
        { "code": "BESCK104E", "credits": 3 },
        { "code": "BETCK105A", "credits": 3 },
        { "code": "BETCK105B", "credits": 3 },
        { "code": "BETCK105C", "credits": 3 },
        { "code": "BETCK105D", "credits": 3 },
        { "code": "BETCK105E", "credits": 3 },
        { "code": "BETCK105F", "credits": 3 },
        { "code": "BETCK105G", "credits": 3 },
        { "code": "BETCK105H", "credits": 3 },
        { "code": "BETCK105I", "credits": 3 },
        { "code": "BETCK105J", "credits": 3 },
        { "code": "BPLCK105A", "credits": 3 },
        { "code": "BPLCK105B", "credits": 3 },
        { "code": "BPLCK105C", "credits": 3 },
        { "code": "BPLCK105D", "credits": 3 },
        { "code": "BPWSK106", "credits": 1 },
        { "code": "BENGK106", "credits": 1 },
        { "code": "BICOK107", "credits": 1 },
        { "code": "BKSKK107", "credits": 1 },
        { "code": "BKBKK107", "credits": 1 },
        { "code": "BSFHK158", "credits": 1 },
        { "code": "BIDTK158", "credits": 1 }
      ],


      "3rd Semester": [
        { code: "BME301", credits: 3 },
        { code: "BME302", credits: 4 },
        { code: "BME303", credits: 4 },
        { code: "BME304", credits: 3 },
        { code: "BMEL305", credits: 1 },
        { code: "BME306A", credits: 3 },
        { code: "BME306B", credits: 3 },
        { code: "BME306C", credits: 3 },
        { code: "BME306D", credits: 3 },
        { code: "BSCK307", credits: 1 },
        { code: "BME358A", credits: 1 },
        { code: "BME358B", credits: 1 },
        { code: "BME358C", credits: 1 },
        { code: "BME358D", credits: 1 },
        { code: "BNSK359", credits: 0 },
        { code: "BPEK359", credits: 0 },
        { code: "BYOK359", credits: 0 },
      ],
  
      "4th Semester": [
        { code: "BME401", credits: 3 },
        { code: "BME402", credits: 4 },
        { code: "BME403", credits: 4 },
        { code: "BME404", credits: 1 },
        { code: "BME405A", credits: 3 },
        { code: "BME405B", credits: 3 },
        { code: "BME405C", credits: 3 },
        { code: "BME405D", credits: 3 },
        { code: "BME456A", credits: 1 },
        { code: "BME456B", credits: 1 },
        { code: "BME456C", credits: 1 },
        { code: "BME456D", credits: 1 },
        { code: "BBOK407", credits: 3 },
        { code: "BUHK408", credits: 1 },
        { code: "BNSK459", credits: 0 },
        { code: "BPEK459", credits: 0 },
        { code: "BYOK459", credits: 0 },
      ],
  
      "5th Semester": [
        { code: "BME501", credits: 3 },
        { code: "BME502", credits: 4 },
        { code: "BME503", credits: 4 },
        { code: "BME504L", credits: 1 },
        { code: "BME515A", credits: 3 },
        { code: "BME515B", credits: 3 },
        { code: "BME515C", credits: 3 },
        { code: "BME515D", credits: 3 },
        { code: "BME586", credits: 2 },
        { code: "BRMK557", credits: 3 },
        { code: "BESK508", credits: 2 },
        { code: "BNSK559", credits: 0 },
        { code: "BPEK559", credits: 0 },
        { code: "BYOK559", credits: 0 },
      ],
    },
  
    CV: {

      "First Year": [
        { "code": "BMATS101", "credits": 4 },
        { "code": "BPHYS102", "credits": 4 },
        { "code": "BPOPS103", "credits": 3 },
        { "code": "BESCK104A", "credits": 3 },
        { "code": "BESCK104B", "credits": 3 },
        { "code": "BESCK104C", "credits": 3 },
        { "code": "BESCK104D", "credits": 3 },
        { "code": "BESCK104E", "credits": 3 },
        { "code": "BETCK105A", "credits": 3 },
        { "code": "BETCK105B", "credits": 3 },
        { "code": "BETCK105C", "credits": 3 },
        { "code": "BETCK105D", "credits": 3 },
        { "code": "BETCK105E", "credits": 3 },
        { "code": "BETCK105F", "credits": 3 },
        { "code": "BETCK105G", "credits": 3 },
        { "code": "BETCK105H", "credits": 3 },
        { "code": "BETCK105I", "credits": 3 },
        { "code": "BETCK105J", "credits": 3 },
        { "code": "BPLCK105A", "credits": 3 },
        { "code": "BPLCK105B", "credits": 3 },
        { "code": "BPLCK105C", "credits": 3 },
        { "code": "BPLCK105D", "credits": 3 },
        { "code": "BENGK106", "credits": 1 },
        { "code": "BPWSK106", "credits": 1 },
        { "code": "BKSKK107", "credits": 1 },
        { "code": "BKBKK107", "credits": 1 },
        { "code": "BICOK107", "credits": 1 },
        { "code": "BIDTK158", "credits": 1 },
        { "code": "BSFHK158", "credits": 1 },
        { "code": "BMATC101", "credits": 4 },
        { "code": "BPHYC102", "credits": 4 },
        { "code": "BCIVC103", "credits": 3 },
        { "code": "BMATE101", "credits": 4 },
        { "code": "BPHYE102", "credits": 4 },
        { "code": "BEEE103", "credits": 3 },
        { "code": "BMATM101", "credits": 4 },
        { "code": "BPHYM102", "credits": 4 },
        { "code": "BEMEM103", "credits": 3 },
        { "code": "BMATS201", "credits": 4 },
        { "code": "BCHES202", "credits": 4 },
        { "code": "BCEDK203", "credits": 3 },
        { "code": "BESCK204A", "credits": 3 },
        { "code": "BESCK204B", "credits": 3 },
        { "code": "BESCK204C", "credits": 3 },
        { "code": "BESCK204D", "credits": 3 },
        { "code": "BESCK204E", "credits": 3 },
        { "code": "BPLCK205A", "credits": 3 },
        { "code": "BPLCK205B", "credits": 3 },
        { "code": "BPLCK205C", "credits": 3 },
        { "code": "BPLCK205D", "credits": 3 },
        { "code": "BETCK205A", "credits": 3 },
        { "code": "BETCK205B", "credits": 3 },
        { "code": "BETCK205C", "credits": 3 },
        { "code": "BETCK205D", "credits": 3 },
        { "code": "BETCK205E", "credits": 3 },
        { "code": "BETCK205F", "credits": 3 },
        { "code": "BETCK205G", "credits": 3 },
        { "code": "BETCK205H", "credits": 3 },
        { "code": "BETCK205I", "credits": 3 },
        { "code": "BETCK205J", "credits": 3 },
        { "code": "BENGK206", "credits": 1 },
        { "code": "BPWSK206", "credits": 1 },
        { "code": "BICOK207", "credits": 1 },
        { "code": "BKSKK207", "credits": 1 },
        { "code": "BKBKK207", "credits": 1 },
        { "code": "BSFHK258", "credits": 1 },
        { "code": "KIDTK258", "credits": 1 },
        { "code": "BMATC201", "credits": 4 },
        { "code": "BCHEC202", "credits": 4 },
        { "code": "BMATE201", "credits": 4 },
        { "code": "BCHEE202", "credits": 4 },
        { "code": "BCEDK203", "credits": 3 },
        { "code": "BMATM201", "credits": 4 },
        { "code": "BCHEM202", "credits": 4 },
        { "code": "BMATS101", "credits": 4 },
        { "code": "BCHES102", "credits": 4 },
        { "code": "BCEDK103", "credits": 3 },
        { "code": "BESCK104A", "credits": 3 },
        { "code": "BESCK104B", "credits": 3 },
        { "code": "BESCK104C", "credits": 3 },
        { "code": "BESCK104D", "credits": 3 },
        { "code": "BESCK104E", "credits": 3 },
        { "code": "BETCK105A", "credits": 3 },
        { "code": "BETCK105B", "credits": 3 },
        { "code": "BETCK105C", "credits": 3 },
        { "code": "BETCK105D", "credits": 3 },
        { "code": "BETCK105E", "credits": 3 },
        { "code": "BETCK105F", "credits": 3 },
        { "code": "BETCK105G", "credits": 3 },
        { "code": "BETCK105H", "credits": 3 },
        { "code": "BETCK105I", "credits": 3 },
        { "code": "BETCK105J", "credits": 3 },
        { "code": "BPLCK105A", "credits": 3 },
        { "code": "BPLCK105B", "credits": 3 },
        { "code": "BPLCK105C", "credits": 3 },
        { "code": "BPLCK105D", "credits": 3 },
        { "code": "BPWSK106", "credits": 1 },
        { "code": "BENGK106", "credits": 1 },
        { "code": "BICOK107", "credits": 1 },
        { "code": "BKSKK107", "credits": 1 },
        { "code": "BKBKK107", "credits": 1 },
        { "code": "BSFHK158", "credits": 1 },
        { "code": "BIDTK158", "credits": 1 }
      ],

      "3rd Semester": [
        { code: "BCV301", credits: 3 },
        { code: "BCV302", credits: 4 },
        { code: "BCV303", credits: 4 },
        { code: "BCV304", credits: 3 },
        { code: "BCV305", credits: 1 },
        { code: "BCV306A", credits: 3 },
        { code: "BCV306B", credits: 3 },
        { code: "BCV306C", credits: 3 },
        { code: "BCV306D", credits: 3 },
        { code: "BSCK307", credits: 1 },
        { code: "BCVL358A", credits: 1 },
        { code: "BCV358B", credits: 1 },
        { code: "BCVL358C", credits: 1 },
        { code: "BCV358D", credits: 1 },
        { code: "BNSK359", credits: 0 },
        { code: "BPEK359", credits: 0 },
        { code: "BYOK359", credits: 0 },
      ],
  
      "4th Semester": [
        { code: "BCV401", credits: 3 },
        { code: "BCV402", credits: 4 },
        { code: "BCV403", credits: 4 },
        { code: "BCVL404", credits: 1 },
        { code: "BCV405A", credits: 3 },
        { code: "BCV405B", credits: 3 },
        { code: "BCV405C", credits: 3 },
        { code: "BCV405D", credits: 3 },
        { code: "BCVL456A", credits: 1 },
        { code: "BCV456B", credits: 1 },
        { code: "BCV456C", credits: 1 },
        { code: "BCV456D", credits: 1 },
        { code: "BBOK407", credits: 3 },
        { code: "BUHK408", credits: 1 },
        { code: "BNSK459", credits: 0 },
        { code: "BPEK459", credits: 0 },
        { code: "BYOK459", credits: 0 },
      ],
  
      "5th Semester": [
        { code: "BCV501", credits: 3 },
        { code: "BCV502", credits: 4 },
        { code: "BCV503", credits: 4 },
        { code: "BCV504", credits: 1 },
        { code: "BCV515A", credits: 3 },
        { code: "BCV515B", credits: 3 },
        { code: "BCV515C", credits: 3 },
        { code: "BCV515D", credits: 3 },
        { code: "BCV586", credits: 2 },
        { code: "BRMK557", credits: 3 },
        { code: "BESK508", credits: 2 },
        { code: "BNSK559", credits: 0 },
        { code: "BPEK559", credits: 0 },
        { code: "BYOK559", credits: 0 },
      ],
      
    }
  };
  
  // Flatten lookup
  const creditLookup = {};
  for (const semMap of Object.values(subjectsByBranch)) {
    for (const subjectList of Object.values(semMap)) {
      subjectList.forEach(({ code, credits }) => {
        creditLookup[code] = credits;
      });
    }
  }
  
  const getGradePoint = (marks) => {
    if (marks >= 90) return 10;
    if (marks >= 80) return 9;
    if (marks >= 70) return 8;
    if (marks >= 60) return 7;
    if (marks >= 50) return 6;
    if (marks >= 40) return 5;
    return 0;
  };
  
  export function calculateSGPA(usn, subjectResults) {
    const branchCode = usn.substring(7, 9).toUpperCase();
    const branch = branchCode;
    if (!subjectsByBranch[branch]) {
      console.warn("Unsupported branch:", branch);
      return { sgpa: null, semester: null, branch: null };
    }
  
    const normalized = subjectResults
    .map(s => {
      const codeNorm = s.code.trim().toUpperCase().replace(/[^A-Z0-9\/]/g, "");
  
      // List of non-subject codes to ignore
      const ignoredCodes = ["PPASS", "FAIL", "FCD", "FIRSTCLASS", "SECONDCLASS", "WITHHELD", "PASS", "AB", "SUBJECTCODE", "NA"];
  
      if (ignoredCodes.includes(codeNorm)) return null;
  
      let credits = creditLookup[codeNorm];
  
      if (credits == null) {
        const base = codeNorm.replace(/[A-Z]$/, "");
        credits = creditLookup[base];
        if (credits == null) {
          const match = Object.keys(creditLookup).find(k => k.startsWith(codeNorm) || codeNorm.startsWith(k));
          if (match) credits = creditLookup[match];
        }
      }
  
      if (credits == null) {
        const isLab = /LAB/i.test(s.title || "") || /L\d{3}/i.test(codeNorm) || /L$/.test(codeNorm);
        credits = isLab ? 1 : 3;
        console.warn(`Unknown subject code: ${codeNorm}, defaulting credits to ${credits}`);
      }
  
      return { code: codeNorm, total: s.total, credits };
    })
    .filter(Boolean); // remove null entries
  
  
    let bestSem = null, bestScore = 0;
    for (const [sem, defs] of Object.entries(subjectsByBranch[branch])) {
      const score = defs.reduce(
        (sum, def) => sum + (normalized.some(r => r.code === def.code || def.code.includes(r.code)) ? def.credits : 0),
        0
      );
      if (score > bestScore) {
        bestScore = score;
        bestSem = sem;
      }
    }
  
    if (!bestSem) {
      console.warn("No semester matched for branch:", branch);
      return { sgpa: null, semester: null, branch };
    }
  
    const semester = bestSem;
    let weightedSum = 0, creditSum = 0;
  
    for (const def of subjectsByBranch[branch][semester]) {
      const match = normalized.find(r =>
        r.code === def.code || def.code.includes(r.code) || r.code.includes(def.code)
      );
      if (match) {
        const gradePoint = getGradePoint(match.total);
        weightedSum += gradePoint * def.credits;
        creditSum += def.credits;
      }
    }
  
    if (creditSum === 0) {
      console.warn("No credits matched for semester", semester);
      return { sgpa: null, semester, branch };
    }
  
    const sgpa = +(weightedSum / creditSum).toFixed(2);
    const percentage = +((weightedSum / creditSum) * 9.5).toFixed(2); // Optional
  
    return { sgpa, semester, branch, percentage };
  }
  